### ISSUE TITLE
Install on linux

### ISSUE THREAD

**Issue by mateorico** [edwardloveall/atom-replacement-icon#5]
How do i install in linux?

**Comment by edwardloveall** [comment]
Hey @mateorico! Great question. I pretty much only use macOS so I'm not 100% sure... I'll do some research to see what I can find.

**Comment by mateorico** [comment]
Hi, i know how change the icon of an application with an image in any format. Just post the icon in a vector image. Thanks!! 
The icon is so cool!!

**Comment by edwardloveall** [comment]
Thanks, I'm glad you like it! I don't actually have a vector version. The shape was created with Blender, a 3D modeling software. Then I exported it to a PNG and cleaned it up with image editing tools for all the different sizes. Can use use a PNG instead? I can definitely make that for you.

**Comment by mateorico** [comment]
Yes, I can use a PNG. I'd appreciate it. Thanks!!

**Comment by edwardloveall** [comment]
Can you try `atom.png` and `file.png` over on the [png-icon branch](https://github.com/edwardloveall/atom-replacement-icon/tree/png-icon) and let me know if those work for you?

**Comment by mateorico** [comment]
Works fine!! Thanks!

![screenshot from 2017-03-30 10-55-43](https://cloud.githubusercontent.com/assets/8517027/24513798/c81cb242-1537-11e7-960b-09a77fdeb52b.png)

To do that, just modify the file /usr/share/applications/atom.desktop in the line
`Icon=atom`
to the PNG image location, like
`Icon=/usr/share/atom/atom-replacement-icon-png-icon/atom.png`

I use gnome-shell 3.18

**Comment by edwardloveall** [comment]
Thanks @mateorico. I'll add this to the `master` branch and update the Readme with your instructions.
