### ISSUE TITLE
Won't install on Mac

### ISSUE THREAD

**Issue by jamauro** [edwardloveall/atom-replacement-icon#7]
When I run the install.sh script, I see these:

cp: ./atom.icns: No such file or directory
cp: ./file.icns: No such file or directory

Any ideas?

**Comment by edwardloveall** [comment]
Hey @jamauro. Thanks for the issue 😄  What directory are you in when running `./install.sh`?

**Comment by jamauro** [comment]
I downloaded your files to my downloads folder. Should I have it elsewhere?

**Comment by edwardloveall** [comment]
It should install from anywhere. Can you send me the output of the following commands?

```shell
pwd
```
and
```shell
ls -la
```

**Comment by ghost** [comment]
Maybe run the command with sudo? 

`sudo ./install.sh`

**Comment by edwardloveall** [comment]
It _shouldn't_ need sudo. Atom isn't a root Application. If that does work, let me know but I'd still love to see the output of those two commands.
